version: '3'

services:
  postgres:
    build: database
    image: panelvw/scrapper-postgresql
    container_name: scrapper-postgresql
    env_file:
      - postgres_secrets.env
    volumes:
      - database:/var/lib/postgresql/data
  
  scrapper:
    build: scrapper
    image: panelvw/scrapper-nodejs
    container_name: scrapper-nodejs
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - postgres_secrets.env
    depends_on:
      - postgres

volumes:
  database:
