version: '3'

services:
  postgres:
    build: database
    image: panelvw/scrapper-postgresql
    restart: always
    container_name: scrapper-postgresql
    env_file:
      - postgres_secrets.env
    volumes:
      - database:/var/lib/postgresql/data
  
  scrapper:
    build: scrapper
    image: panelvw/scrapper-nodejs
    restart: always
    container_name: nodejs
    environment:
      - POSTGRES_HOST=postgres
    env_file:
      - postgres_secrets.env
    depends_on:
      - postgres
    volumes:
      - scrapperLog:/var/log/scrapper/

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      restart: unless-stopped
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  database:
  pgadmin:
  scrapperLog:
